### ISSUE TITLE
User reports have bad data

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/reportbooru#13]
Since the August 13th note report where the filesize was zero, the subsequent reports are such that all of the data points are zero.

https://isshiki.donmai.us/user-reports/notes/2017-08-13_v1.html (Filesize is zero)
https://isshiki.donmai.us/user-reports/notes/2017-08-20_v1.html (All data is zero)
https://isshiki.donmai.us/user-reports/notes/2017-08-27_v1.html (All data is zero)

**Comment by BrokenEagle** [comment]
The same thing is also happening to the wiki pages report, although there was no incidence of filesize being zero for them.

https://isshiki.donmai.us/user-reports/wiki_pages/2017-08-20_v1.html (All data is zero)
https://isshiki.donmai.us/user-reports/wiki_pages/2017-08-27_v1.html (All data is zero)

**Comment by r888888888** [comment]
So there are limitations on how far back I can stream old versioned data into the partitioned tables, so it will have to skip to the most recent 31 days. I've added checks to reconnect to the Postgres database when the connection fails so hopefully this will happen less frequently in the future.
