### ISSUE TITLE
Discrepancy for rating percentages in uploads report

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/reportbooru#16]
It was reported by Chiara that the percentages for the ratings on the upload reports don't add up to 100%.  This appears to be because the numbers are being truncated to integers.

https://github.com/r888888888/reportbooru/blob/master/app/models/reports/uploads.rb#L22-L24

Switching the format string to ``"%.1f%%"`` would alleviate this discrepancy, although to eliminate it the numbers would need to be rounded down to whichever decimal point is being used.

**Comment by r888888888** [comment]
I think `%.0f%%` is good enough.
