### ISSUE TITLE
Missing names on inactive approvers report

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/reportbooru#17]
Comparing the list of [all approvers](http://danbooru.donmai.us/users?commit=Search&search%5Bcan_approve_posts%5D=true&search%5Border%5D=date&utf8=%E2%9C%93&limit=100) with the list of [active approvers](http://isshiki.donmai.us/user-reports/approvers/2017-10-15_v4.json) and [inactive approvers](http://isshiki.donmai.us/user-reports/inactive_approvers/2017-10-15_v2.json) seems to be missing a lot of names.  The following list is what I came up with after I did a comparison.

['Arantheus', 'TheStupidOne', 'buehbueh', 'Bloodletter', 'jxh2154', 'bigrich', 'CaptainLoony', 'alicemaiwaifu', 'Xz', 'memento_mori', 'MagicalAsparagus', 'Toks', 'wareya', 'ePlus', 'Altered']

All of these approvers seem to have no approvals during the report period, so maybe it's not including approvers with zero uploads?

**Comment by r888888888** [comment]
This is complicated because there are technically 494 approvers in total. I'm not sure how these should be filtered.
