### ISSUE TITLE
Incorrect URL links for user accounts on Inactive Approvers report

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/reportbooru#18]
With the switch to version 3 on the Inactive Approvers report, it seems like a variable isn't being properly dereferenced and so it spits out the object reference instead.

Example:

https://danbooru.donmai.us/users/#<DanbooruRo::User:0x0055c1a88e6790>

Version 2 (without issue): http://isshiki.donmai.us/user-reports/inactive_approvers/2017-10-22_v2.html
Version 3 (with issue): http://isshiki.donmai.us/user-reports/inactive_approvers/2017-10-29_v3.html

As an additional issue, it seems like there is some kind of text encoding error going on with the Inactive Approvers report, as one of the users is listed as **ä¸€å£°**, when such a user [doesn't even exist](http://danbooru.donmai.us/users?name=%C3%A4%C2%B8%E2%82%AC%C3%A5%C2%A3%C2%B0).  It sort of looks like garbled Kanji characters, and sure enough when I manually switched the encoding to UTF-8 the name instead read as 一声 which [does exist](https://danbooru.donmai.us/users?name=%E4%B8%80%E5%A3%B0).  Checking the other reports, it seems like this encoding issue only exists on the Inactive Approvers report.

**Comment by r888888888** [comment]
fixed in bfe74f46d12d4e25af99112620cc34c4af67aa83
