### ISSUE TITLE
Inactive Report incorrectlty selects unlimited uploaders

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/reportbooru#19]
It lists many users that don't even have the Approve Posts permission.  Instead, it looks like it's selecting those with the Unlimited Uploads permission

According to the User model on Danbooru, the **can_approve_posts** bit is in the 14th position.

https://github.com/r888888888/danbooru/blob/master/app/models/user.rb#L37-L59

Therefore, the value 1 should be bit-shifted to the left 13 places and not 14 to get it into the right position.

https://github.com/r888888888/reportbooru/blob/master/app/models/reports/inactive_approvers.rb#L49

**Comment by r888888888** [comment]
fixed in 972402f5bf35f5bde6c04414d0dc2f8b8a72bdc2
