### ISSUE TITLE
Don't include Meta tags in missing tags report

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/reportbooru#20]
From the [Danbooru forum](http://danbooru.donmai.us/forum_posts/140041):

> Chiera said:
> 
> Can we PLEASE kick out the mention from the DanbooruBot that I should consider using [[bad_id]] in the future?
> 
> Thanks :3.

Basically, some users are being told to add **bad_id**, and I've also heard mention of **md5_mismatch** amongst others.  This should not be.  In fact, none of the Meta tags should be part of the missing tags report.  They should be filtered out of the equation.

**Comment by r888888888** [comment]
Is there a full list of these sorts of tags anywhere?

**Comment by BrokenEagle** [comment]
Does Reportbooru have access to tag categories?  I'd think so, since if I recall correctly a couple of the reports distinguish between **General**, **Artist**, **Character**, and **General** tags.  If so, just exclude those that have the **Meta** category?

If not, the list would need to be imported from Danbooru.
http://danbooru.donmai.us/tags?search[category]=5&limit=200
