### ISSUE TITLE
Split post changes report by user level

### ISSUE THREAD

**Issue by evazion** [r888888888/reportbooru#21]
For uploads there are two reports, one for Builders and one for Members. The post changes report should also be split between Builders and non-Builders. This would be useful both for detecting vandalism, and for identifying users to promote.

Related issue: the tag vandalism report is currently limited to Members. It should instead be non-Builders, so that it includes Gold and Platinium.

Ref: https://danbooru.donmai.us/forum_topics/14945.

**Comment by r888888888** [comment]
Done.
