### ISSUE TITLE
Unicode usernames don't render correctly

### ISSUE THREAD

**Issue by evazion** [r888888888/reportbooru#22]
Usernames containing Unicode characters don't render correctly:

![image](https://user-images.githubusercontent.com/8430473/35596963-d0e1a3a6-05e1-11e8-9e6b-06c22974e363.png)

The problem is that the page doesn't declare that it's in UTF-8. Need to either add `<meta charset="utf-8">`, or configure the webserver to send `Content-Type: text/html; charset=utf8`.

**Comment by r888888888** [comment]
Fixed in Nginx.
