### ISSUE TITLE
The minimum number of items for each report is off by 1

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/reportbooru#23]
> skylightcrystal said ([forum #1234](https://danbooru.donmai.us/forum_posts/150404)):
> 
> It's a very minor issue, but I think the minimum number of uploads for the top tagger report on isshiki (https://isshiki.donmai.us/user-reports/taggers/) is actually 51, not 50. I have uploaded 50 images in the last 30 days but am not on the list, whereas those who have uploaded 51 images are on there. Looking back I couldn't see any times in the past when people have been included in the list with precisely 50 uploads.
> 
> The comments one also seems to have a minimum count of 11, not the stated 10.

I looked through all of the models in the reports directory, and the greater than operator ">" is being used for almost all of them, which would of course not include the number it's comparing against.

https://github.com/r888888888/reportbooru/blob/5d345fc286b3b54c24c1a29cfbebe6610900462c/app/models/reports/taggers.rb#L77
https://github.com/r888888888/reportbooru/blob/5d345fc286b3b54c24c1a29cfbebe6610900462c/app/models/reports/comments.rb#L87

Instead the greater than or equal to operator ">=" should be used.  The only report that is currently using that operator is the approvers report.  All of the other reports need to be fixed.

**Comment by r888888888** [comment]
Fixed. I've switched them all to use `>=` where appropriate.
