### ISSUE TITLE
Inaccurate deletion confidence percentages for the member upload report

### ISSUE THREAD

**Issue by ghost** [r888888888/reportbooru#25]
Noticed that the deletion confidence percentages are way off with [the most recent member upload report.](https://isshiki.donmai.us/user-reports/member_uploads/2018-09-16_v5.html)
EX: Juan.Dela.Cruz is listed with 113 posts in the past month with 98 deleted. 98/113=87%. However, his deletion confidence is listed as 79%, a whole 9% off.

**Comment by r888888888** [comment]
Firstly, a 79% deletion confidence does not mean the same thing as 79% of his posts are expected to get deleted. It's a technical term but rather it means that in 79 out of 100 trials, you would expect at least 98 of 113 of his uploads to get deleted. 

This is how the confidence intervals work. 113 posts is not that much data. The uncertainty in not having a larger sample size is baked into the percentage. And this is the lower bound so it represents the most optimistic portrayal of the data.

79% is still a huge outlier so the CI is doing it's job here.
