### ISSUE TITLE
Change Naming of Vandalism Report

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/reportbooru#6]
As mentioned on the [Danbooru Forums](http://danbooru.donmai.us/forum_topics/13112?page=9#forum_post_123685).

Basically, the name of the report carries a negative connotation, even when the activity that occurs may not necessarily be malicious. User Jarlath had the best suggestion for a name change.

> I'd be calling it "mass tag changes" as that describes the activity, and most of those changes look like valid gardening activities to me.

Also, this might be a separate issue, but he also brought up the idea of including Gold and Platinum level users in the report in addition to Member-level users.

> Would it be worth including the gold and platinum members, in case there's some sort of edit war?

It might be worth just to try that out... if it clutters up the report, it could always be reverted back.

**Comment by r888888888** [comment]
I'd rather just add a disclaimer indicating not all listed users may be vandals. The intent of the report is to find vandalism so I think the title is accurate.

As for gold/platinum members, the problem there is it sucks in a lot of legitimate bulk changes that people tend to use with tag scripts. I think it's just add more noise.
